import { Injectable, signal, computed } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class LanguageService {
  currentLang = signal<'es' | 'en'>('es');

  private dictionary: any = {
    es: {
        // Navbar
        recetas: 'Recetas', 
        productos: 'Productos', 
        subir_receta: 'Subir receta', 
        contacto: 'Contacto',
        salir: 'Salir', 
        hola: 'Hola,', 
        login: 'Inicia Sesión', 
        registro: 'Regístrate',
        // Hero
        hero_badge: 'Especialistas en Málaga ☀️', hero_titulo: 'Bienvenido a',
        hero_desc: 'Descubre las recetas más reputadas y seguras.',
        hero_saludo_user: '¡Qué bueno verte de nuevo,', hero_invitado: 'Únete a nuestra comunidad',
        //chatbot
        chat_bienvenida: '¡Hola! 👋 Soy el asistente de SafeBite. ¿En qué puedo ayudarte?',
        chat_header: 'Asistente SafeBite',
        chat_placeholder: 'Escribe tu duda...',
        chat_opt_alergias: 'Alergias Comunes',
        chat_opt_funciona: '¿Cómo funciona?',
        chat_opt_contacto: 'Contacto',
        chat_resp_alergias: 'En SafeBite detectamos alérgenos como gluten, lácteos y frutos secos. ¿Buscas alguno en concreto?',
        chat_resp_gluten: '¡Entendido! Puedes activar el filtro de "Sin Gluten" en tu perfil para que todas las recetas se adapten a ti.',
        chat_resp_funciona: 'Es muy fácil: escanea o busca una receta y te diremos si es segura para tus alergias configuradas.',
        chat_resp_contacto: '¡Perfecto! Te redirijo a nuestra página de contacto para que puedas escribirnos directamente.',
        chat_resp_error: 'No estoy seguro de entenderte, pero puedo informarte sobre alérgenos o sobre nuestra app.',
        chat_escribiendo: 'El asistente está escribiendo...',
        chat_ir_contacto: 'Ir a Contacto',
        chat_ir_recetas: 'Ver Recetas',
        // recetas
        rec_titulo: 'Nuestro Catálogo de Recetas',
        rec_buscar_placeholder: 'Busca una receta...',
        rec_filtros_label: 'Filtros inteligentes:',
        rec_no_resultados: 'No se encontraron recetas',
        rec_no_resultados_desc: 'Prueba a cambiar el nombre o quitar algunos filtros de alérgenos.',
        rec_cargando: 'Cargando recetas de SafeBite...',
        cat_entrantes: 'Entrantes',
        cat_principales: 'Platos Principales',
        cat_postres: 'Postres',
        rec_ver_receta: 'Ver receta',
        btn_asistente: 'Asistente',
        // Filtros específicos
        filter_gluten: 'Sin Gluten',
        filter_lactose: 'Sin Lactosa',
        filter_egg: 'Sin Huevo',
        // ETIQUETAS "SIN" (Usadas en varios sitios)
        tag_gluten: 'Sin gluten',
        tag_lactosa: 'Sin lactosa',
        tag_frutos_secos: 'Sin frutos secos',
        tag_huevo: 'Sin huevo',
        tag_pescado: 'Sin pescado',
        tag_soja: 'Sin soja',
        //filtro
        alg_gluten: 'Gluten',
        alg_lactosa: 'Lactosa',
        alg_huevo: 'Huevo',
        alg_frutos_secos: 'Frutos Secos',
        alg_soja: 'Soja',
        alg_marisco: 'Marisco',
        alg_pescado: 'Pescado',
        // PÁGINA PRODUCTOS
        // Título con parte verde
        prod_titulo_pre: '¿En qué ',
        prod_titulo_verde: 'Supermercado',
        prod_titulo_post: ' vas a buscar?',
        prod_subtitulo: 'Analizaremos los productos según tu perfil de salud.',
        prod_btn_analizar: 'Analizar',
        prod_btn_volver: '← Cambiar Tienda',
        prod_label_rapido: 'Selección rápida de alérgenos:',
        prod_label_mis_etiquetas: 'Mis etiquetas personalizadas:',
        prod_placeholder_anadir: 'Añadir otro...',
        prod_placeholder_buscar: 'Busca un producto...',
        prod_no_seguro: '⚠️ NO SEGURO',
        // PÁGINA SUBIR RECETA
        sub_nueva: 'Nueva Receta',
        sub_foto_instruccion: 'Subir foto de la receta',
        sub_label_titulo: 'Título de la receta',
        sub_ph_titulo: 'Ej: Tortilla de Patatas Clásica',
        sub_label_cat: 'Categoría',
        sub_label_ing: 'Ingredientes',
        sub_ph_ing: 'Añadir ingrediente (ej: 4 patatas)',
        sub_label_pasos: 'Pasos de preparación',
        sub_ph_pasos: 'Añadir paso (ej: Freír patatas)',
        sub_label_tags: 'Etiquetas "Sin":',
        sub_btn_publicar: 'Publicar Receta',
        sub_publicando: 'Publicando...',
        // Página Contacto
        con_titulo: 'Contacta con nosotros',
        con_subtitulo: 'Estamos para ayudarte 🍃',
        con_desc: 'En SafeBite nos tomamos muy en serio la seguridad alimentaria. Escríbenos si tienes dudas sobre alérgenos, recetas o el uso de la plataforma.',
        con_feat1: 'Respuesta en menos de 24h',
        con_feat2: 'Asesoramiento sobre alérgenos',
        con_feat3: 'Soporte humano y cercano',
        con_form_header: 'Contacto SafeBite',
        con_form_sub: 'Te ayudaremos en menos de 24h.',
        con_label_nombre: 'Nombre completo',
        con_placeholder_nombre: 'Ej. Juan Pérez',
        con_label_email: 'Correo electrónico',
        con_label_mensaje: 'Tu mensaje',
        con_placeholder_mensaje: 'Cuéntanos detalladamente tu consulta...',
        con_btn_enviar: 'Enviar Mensaje',
        con_privacidad: '🔒 Tus datos están protegidos y no se compartirán con terceros.'
      },
      en: {
        // Navbar
        recetas: 'Recipes', productos: 'Products', subir_receta: 'Upload Recipe', contacto: 'Contact',
        salir: 'Logout', hola: 'Hello,', login: 'Login', registro: 'Register',
        //chatbot
        chat_header: 'SafeBite Assistant',
        chat_placeholder: 'Write your question...',
        chat_bienvenida: 'Hi! 👋 I am the SafeBite assistant. How can I help you?',
        chat_opt_comunes: 'Common Allergens',
        chat_opt_funciona: 'How it works?',
        chat_opt_contacto: 'Contact',
        chat_resp_alergias: 'At SafeBite we detect allergens such as gluten, dairy and nuts. Are you looking for a specific one?',
        chat_resp_gluten: 'Understood! You can activate the "Gluten-Free" filter in your profile so that all recipes adapt to you.',
        chat_resp_funciona: 'It is very easy: scan or search for a recipe and we will tell you if it is safe for your configured allergies.',
        chat_resp_contacto: 'Perfect! I am redirecting you to our contact page so you can write to us directly.',
        chat_resp_error: 'I am not sure I understand you, but I can inform you about allergens or our app.',
        chat_escribiendo: 'Assistant is typing...',
        chat_ir_contacto: 'Go to Contact',
        chat_ir_recetas: 'View Recipes',
        // Hero
        hero_badge: 'Specialists in Malaga ☀️', hero_titulo: 'Welcome to',
        hero_desc: 'Discover the most reputable and safe recipes.',
        hero_saludo_user: 'Great to see you again,', hero_invitado: 'Join our community',
        // Página Recetas
        rec_titulo: 'Our Recipe Catalog',
        rec_buscar_placeholder: 'Search for a recipe...',
        rec_filtros_label: 'Smart filters:',
        rec_no_resultados: 'No recipes found',
        rec_no_resultados_desc: 'Try changing the name or removing some allergen filters.',
        rec_cargando: 'Loading SafeBite recipes...',
        cat_entrantes: 'Starters',
        cat_principales: 'Main Courses',
        cat_postres: 'Desserts',
        rec_ver_receta: 'View recipe',
        btn_asistente: 'Assistant',
        // Filtros específicos
        filter_gluten: 'Gluten Free',
        filter_lactose: 'Lactose Free',
        filter_egg: 'Egg Free',
        // ETIQUETAS "SIN"
        tag_gluten: 'Gluten free',
        tag_lactosa: 'Lactose free',
        tag_frutos_secos: 'Nut free',
        tag_huevo: 'Egg free',
        tag_pescado: 'Fish free',
        tag_soja: 'Soy free',
        //filtro
        alg_gluten: 'Gluten',
        alg_lactosa: 'Lactose',
        alg_huevo: 'Egg',
        alg_frutos_secos: 'Nuts',
        alg_soja: 'Soy',
        alg_marisco: 'Shellfish',
        alg_pescado: 'Fish',
        // Página Productos (Supermercados)
        prod_titulo_pre: 'Which ',
        prod_titulo_verde: 'Supermarket',
        prod_titulo_post: ' are you searching in?',
        prod_subtitulo: 'We will analyze products based on your health profile.',
        prod_btn_analizar: 'Analyze',
        prod_btn_volver: '← Change Store',
        prod_label_rapido: 'Quick allergen selection:',
        prod_label_mis_etiquetas: 'My custom tags:',
        prod_placeholder_anadir: 'Add another...',
        prod_placeholder_buscar: 'Search a product...',
        prod_no_seguro: '⚠️ NOT SAFE',
        // Página Subir Receta
        sub_nueva: 'New Recipe',
        sub_foto_instruccion: 'Upload recipe photo',
        sub_label_titulo: 'Recipe Title',
        sub_ph_titulo: 'e.g.: Classic Spanish Omelette',
        sub_label_cat: 'Category',
        sub_label_ing: 'Ingredients',
        sub_ph_ing: 'Add ingredient (e.g.: 4 potatoes)',
        sub_label_pasos: 'Preparation Steps',
        sub_ph_pasos: 'Add step (e.g.: Fry potatoes)',
        sub_label_tags: '"Free-from" Tags:',
        sub_btn_publicar: 'Publish Recipe',
        sub_publicando: 'Publishing...',
        // Página Contacto
        con_titulo: 'Contact us',
        con_subtitulo: 'We are here to help 🍃',
        con_desc: 'At SafeBite, we take food safety very seriously. Write to us if you have questions about allergens, recipes, or using the platform.',
        con_feat1: 'Response in less than 24h',
        con_feat2: 'Allergen advice',
        con_feat3: 'Personal and friendly support',
        con_form_header: 'SafeBite Contact',
        con_form_sub: 'We will help you within 24h.',
        con_label_nombre: 'Full name',
        con_placeholder_nombre: 'e.g. John Doe',
        con_label_email: 'Email address',
        con_label_mensaje: 'Your message',
        con_placeholder_mensaje: 'Tell us about your inquiry in detail...',
        con_btn_enviar: 'Send Message',
        con_privacidad: '🔒 Your data is protected and will not be shared with third parties.'
    }
  };

  t = computed(() => this.dictionary[this.currentLang()]);

  setLanguage(lang: 'es' | 'en') {
    this.currentLang.set(lang);
  }
}