name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - web  # ← tu rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./safebite-web
        run: npm install --legacy-peer-deps

      - name: Build
        working-directory: ./safebite-web
        run: npm run build -- --configuration production

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
